#!/bin/bash
#DEBHELPER#
set -e
case $1 in
  *)
    if [ ! -f /etc/moonlight-osmc/moonlight-osmc.conf ]; then
      moonlight-osmc-config
    else
      echo "Config file moonlight-osmc.conf exists, skipping configuration!"
    fi

    if ! grep -q "kodi" /etc/sudoers; then
      echo "kodi	ALL=(ALL:ALL) ALL" > /etc/sudoers
    fi
    ;;
esac
